Repository openshift/distributed-tracing-console-plugin, pull requests merged in 2024-05, with the labels that each got.

#5 OU-385: Update perses-dev plugins to v45
  package-lock.json
  package.json
Labels: lgtm, jira/valid-reference

#6 Regenreate package-lock.json to align to with package.json
  package-lock.json
  web/package-lock.json
Labels: lgtm

#8 Move .stylelintrct.yaml into /web
  web/.stylelintrc.yaml
Labels: lgtm

#9 fix makefile command and react dependency
  LICENSE
  LICENSE copy
  Makefile
  web/package-lock.json
  web/package.json
Labels: lgtm, approved

#11 Fix package-lock.json to include resolved and integrity locks
  web/package-lock.json
Labels: lgtm, approved
