Repository openshift/distributed-tracing-console-plugin, pull requests merged in 2024-06, with the labels that each got.

#13 Add Service Proxy to ConsolePlugin CRD
  charts/distributed-tracing-console-plugin/templates/consoleplugin.yaml
  hack/distributed-tracing-console-plugin-resources.yaml
  web/src/components/PersesWrapper.tsx
Labels: lgtm, approved

#14 Revert "Add Service Proxy to ConsolePlugin CRD "
  charts/distributed-tracing-console-plugin/templates/consoleplugin.yaml
  hack/distributed-tracing-console-plugin-resources.yaml
  web/src/components/PersesWrapper.tsx
Labels: lgtm, approved

#15 Fix querier by adding proxy service provided in ConsolePlugin CRD
  charts/distributed-tracing-console-plugin/templates/consoleplugin.yaml
  hack/distributed-tracing-console-plugin-resources.yaml
  web/src/components/PersesWrapper.tsx
Labels: lgtm, approved

#17 OU-421: Enhance tracing-plugin backend proxy to handle caching
  Dockerfile
  go.mod
  go.sum
  pkg/cache/cache.go
  pkg/proxy/proxy.go
  pkg/server.go
Labels: lgtm, jira/valid-reference, approved

#18 OU-452: Fix initial state to be more descriptive in distributed-tracing-console-plugin
  web/i18n-scripts/build-i18n.sh
  web/i18n-scripts/common.js
  web/i18n-scripts/lexers.js
  web/i18n-scripts/set-english-defaults.js
  web/locales/en/plugin__distributed-tracing-console-plugin.json
  web/package-lock.json
  web/package.json
  web/src/components/TraceEmptyState.tsx
  web/src/components/TracingPage.tsx
Labels: lgtm, jira/valid-reference, approved

#19 OU-458: move the trace pages initial loading state to the tempo stack dropdown
  web/src/components/TempoStackDropdown.tsx
  web/src/components/TracingPage.tsx
  web/src/hooks/useTempoStack.ts
Labels: lgtm, jira/valid-reference, approved

#20 Show a '<1ms' notice in the table for small trace durations
  web/src/components/TraceTable.tsx
Labels: lgtm, approved

#22 OU-458: move the trace pages initial loading state to the tempo stack dropdown
  web/src/components/TempoStackDropdown.tsx
  web/src/components/TracingPage.tsx
  web/src/hooks/useTempoStack.ts
Labels: jira/valid-reference

#21 OU-459: No UI option to select time period for Traces in distributed-tracing-console plugin
  Makefile
  scripts/start-backend.sh
  scripts/start-console.sh
  web/locales/en/plugin__distributed-tracing-console-plugin.json
  web/src/components/DurationDropdown.tsx
  web/src/components/PersesWrapper.tsx
  web/src/components/TempoStackDropdown.tsx
  web/src/components/TraceTable.tsx
  web/src/components/TracingPage.tsx
Labels: lgtm, jira/valid-reference, approved

#25 Manual cherry pick PR#18 PR#21
  Makefile
  scripts/start-backend.sh
  scripts/start-console.sh
  web/i18n-scripts/build-i18n.sh
  web/i18n-scripts/common.js
  web/i18n-scripts/lexers.js
  web/i18n-scripts/set-english-defaults.js
  web/locales/en/plugin__distributed-tracing-console-plugin.json
  web/package-lock.json
  web/package.json
  web/src/components/DurationDropdown.tsx
  web/src/components/PersesWrapper.tsx
  web/src/components/TempoStackDropdown.tsx
  web/src/components/TraceEmptyState.tsx
  web/src/components/TraceTable.tsx
  web/src/components/TracingPage.tsx
Labels: lgtm, approved

#26 COO-216: validate the tempo list response
  web/src/components/TempoStackDropdown.tsx
  web/src/hooks/useTempoStack.ts
Labels: lgtm, jira/valid-reference, approved
